<?php

/**
* @uberhacker
*		 from @uberhacker
*
*		function hook_form_FORM_ID_alter(&$form, &$form_state, $form_id) {
*		  foreach ($form as $key => $value) {
*		    $form[$key]['#weight'] = rand(-100, 100);
*		  }
*		}
*  replace `hook` with your custom module name and `FORM_ID` with the webform id.
**/

function webform_random_form_webform_configure_form_alter(&$form, &$form_state, $form_id) {
	/* Random Settings */
	$form['random'] = array(
		'#type' => 'checkbox',
		'#default_value' => variable_get('webform_random_randomize_'.$form['nid']['#value'], 0 ),
		'#title' => t('Randomize form elements'),
		);
	$form['actions']['submit']['#submit'][] = 'webform_random_save_submit';
}
function webform_random_save_submit ($form, &$form_state) {
	variable_set('webform_random_randomize_'.$form['nid']['#value'], $form_state['values']['random']);
}


function webform_random_form_alter(&$form, &$form_state, $form_id) {
	dpm ($form);
	if (substr($form_id, 0, 20) == 'webform_client_form_' && variable_get('webform_random_randomize_'.$form['#node']->nid, 0 )) {
		foreach	($form['submitted'] as $key => $value) {
			if (is_array($value)) {
				$form['submitted'][$key]['#weight'] = rand(-100, 100);
			} 
		}
	}

}

