<?php
/**
 * @file
 * This module provides a checkbox on the WebformForm Form Settings page located
 * located at /node/%/webform/configure to display all form elements randomly.
 *
 * Contributions by Brandon Williams (@rocketeerbkw) and Ed Reel (@uberhacker)
 *
 * @author Nick Landis (@BiigNiick)
 */

function webform_random_form_webform_configure_form_alter(&$form, &$form_state, $form_id) {
  /* Random Settings */
  $form['random'] = array(
  // make a checkbox
  '#type' => 'checkbox',
    // put it at the top of the list
    '#weight' => '-100',
    // set a varible in the database that is unique to the webform
    '#default_value' => variable_get('webform_random_randomize_'.$form['nid']['#value'], 0 ),
    // label the checkbox so people know what it does
    '#title' => t('Randomize top-level form elements'),
    );
//clicking submit calls a function
$form['#submit'][] = '_webform_random_form_submit_save';
}

/**
 * Implements hook_form_submit().
 */
function _webform_random_form_submit_save ($form, &$form_state) {
  // set a variable when saving the form
  variable_set('webform_random_randomize_'.$form['nid']['#value'], $form_state['values']['random']);
}

/**
 * Implements hook_form_alter().
 */
function webform_random_form_alter(&$form, &$form_state, $form_id) {
  // if it is a webform get the variable for that node is set
  if (substr($form_id, 0, 20) == 'webform_client_form_' && variable_get('webform_random_randomize_'.$form['#node']->nid, 0 )) {
    // go through each item in the form
    foreach	($form['submitted'] as $key => $value) {
      // if the $value for the item is an array
      if (is_array($value)) {
        // change the array element of weight to a random number between -100 and 100
        $form['submitted'][$key]['#weight'] = rand(-100, 100);
      }
    }
  }
}

