<?php

/**
 * @file
 * Webform Random Fieldset module.
 *
 * Adds a random fieldset component that randomizes all fields contained within.
 *
 * @author Nick Landis (@BiigNiick)
 */

/**
 * Implements hook_form_alter().
 */
function webform_random_fieldset_form_webform_component_edit_form_alter(&$form, &$form_state, $form_id) {
  /* Random Fieldset Settings */
  // if this component is a fieldset
  if ($form['type']['#value'] == 'fieldset') {
    // make a random_fieldset array in $form
    $form['random_fieldset'] = array(
      // it's a checkbox
    '#type' => 'checkbox',
      // at the top of the list
      '#weight' => '-100',
      // check to see if this component has a varialbe saved for it already
      // and reflect that setting as the default value
      '#default_value' => variable_get('webform_random_fieldset_randomize_'.$form['cid']['#value'], 0 ),
      // label the checkbox with something that makes sense
      '#title' => t('Randomize fieldset elements'),
    );
// save the variable and the whole form
// saving other elements in the form is not working...
//  SOMETHING NOT WORKING CORRECTLY HERE
$form['actions']['submit']['#submit'][] = 'webform_random_fieldset_save_submit';
  }
}
//  not sure why we need this, but it breaks even more without it...
function webform_random_fieldset_save_submit ($form, &$form_state) {
  variable_set('webform_random_fieldset_randomize_'.$form['cid']['#value'], $form_state['values']['random_fieldset']);
}

/**
 * Implements hook_form_alter().
 */
function webform_random_fieldset_form_alter(&$form, &$form_state, $form_id) {
  // This is where the randomness happens.
  // if its a webform
  if (substr($form_id, 0, 20) == 'webform_client_form_') {
    // for every webform component get the key-value
    foreach ($form['submitted'] as $key => $value ) {
      // if the component is a fieldset
      if ($form['submitted'][$key]['#type'] == 'fieldset') {
        // set a varialbe called cid to the fieldset's component ID
        $cid = $form['submitted'][$key]['#webform_component']['cid'];
        // is the webform_random_fieldset checkbox checked
        $checked = variable_get('webform_random_fieldset_randomize_'.$cid);
        // if the random checkbox is checked
        if ($checked) {
          // go through each element in the fieldset
          foreach ($form['submitted'][$key] as $fieldset_key => $fieldset_value) {
            // check to see if the $value for the item is an array
            if (is_array($fieldset_value)) {
              // change the array element of weight to a random number between -100 and 100
              $form['submitted'][$key][$fieldset_key]['#weight'] = rand(-100, 100);
            }
          }
        }
      }
    }
  }
}
